use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    schemars,
    service::RequestContext,
    tool, tool_handler, tool_router, ErrorData as McpError, RoleServer, ServerHandler,
};
use serde_json::json;

use crate::api_client::{ApiClient, ListEventTypesFilters};

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListEventTypesArgs {
    /// Filter by status (e.g. CURRENT, ARCHIVED).
    #[serde(default)]
    pub status: Option<String>,
    /// Filter by application code.
    #[serde(default)]
    pub application: Option<String>,
    /// Filter by subdomain code.
    #[serde(default)]
    pub subdomain: Option<String>,
    /// Filter by aggregate code.
    #[serde(default)]
    pub aggregate: Option<String>,
    /// Filter by client ID (admin-scoped tokens only).
    #[serde(default, rename = "clientId")]
    pub client_id: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GetByIdArgs {
    /// Resource ID.
    pub id: String,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GetSchemaArgs {
    /// Event type ID.
    pub id: String,
    /// Schema version (e.g. "1.0"). If omitted, returns the CURRENT version.
    #[serde(default)]
    pub version: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListSubscriptionsArgs {
    /// Filter by client ID (admin-scoped tokens only).
    #[serde(default, rename = "clientId")]
    pub client_id: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListApplicationsArgs {
    /// If false, include inactive applications. Defaults to active-only.
    #[serde(default)]
    pub active: Option<bool>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListRolesArgs {
    /// Filter by source (e.g. CODE, BOOTSTRAP, API, UI).
    #[serde(default)]
    pub source: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GetOpenApiArgs {
    /// Application code. Defaults to "platform" — the FlowCatalyst
    /// control-plane API itself, which is what most agents want.
    #[serde(default, rename = "applicationCode")]
    pub application_code: Option<String>,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GetApplicationCapabilitiesArgs {
    /// Application code (e.g. "platform", "orders").
    #[serde(rename = "applicationCode")]
    pub application_code: String,
}

#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct EmptyArgs {}

#[derive(Clone)]
pub struct FcMcpServer {
    api: Arc<ApiClient>,
    // Consumed by code generated by `#[tool_router]`; clippy can't see that
    // through the macro expansion.
    #[allow(dead_code)]
    tool_router: ToolRouter<FcMcpServer>,
}

#[tool_router]
impl FcMcpServer {
    pub fn new(api: Arc<ApiClient>) -> Self {
        Self {
            api,
            tool_router: Self::tool_router(),
        }
    }

    #[tool(
        description = "List event types registered in FlowCatalyst. Optionally filter by status, application, subdomain, aggregate, or client ID."
    )]
    async fn list_event_types(
        &self,
        Parameters(args): Parameters<ListEventTypesArgs>,
    ) -> Result<CallToolResult, McpError> {
        let filters = ListEventTypesFilters {
            status: args.status.as_deref(),
            application: args.application.as_deref(),
            client_id: args.client_id.as_deref(),
            subdomain: args.subdomain.as_deref(),
            aggregate: args.aggregate.as_deref(),
        };
        match self.api.list_event_types(&filters).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Get detailed information about a specific event type, including all schema versions."
    )]
    async fn get_event_type(
        &self,
        Parameters(args): Parameters<GetByIdArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.get_event_type(&args.id).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Get the raw JSON Schema for a specific event type version. Defaults to the CURRENT version."
    )]
    async fn get_schema(
        &self,
        Parameters(args): Parameters<GetSchemaArgs>,
    ) -> Result<CallToolResult, McpError> {
        let event_type = match self.api.get_event_type(&args.id).await {
            Ok(v) => v,
            Err(e) => return Ok(error_text(e)),
        };

        let versions = event_type
            .get("specVersions")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();

        let chosen = match args.version.as_deref() {
            Some(v) => versions
                .iter()
                .find(|sv| sv.get("version").and_then(|s| s.as_str()) == Some(v)),
            None => {
                // Prefer the CURRENT version (operator-promoted) but fall
                // back to FINALISING. Synced schemas (SDK push, fc-dev's
                // platform-event-types auto-sync) land in FINALISING and
                // stay there until an operator promotes them in the UI;
                // without this fallback, agents would see no schema at all
                // on a freshly-seeded dev environment.
                let status_eq = |sv: &&serde_json::Value, target: &str| -> bool {
                    sv.get("status").and_then(|s| s.as_str()) == Some(target)
                };
                versions
                    .iter()
                    .find(|sv| status_eq(sv, "CURRENT"))
                    .or_else(|| versions.iter().find(|sv| status_eq(sv, "FINALISING")))
            }
        };

        let Some(spec) = chosen else {
            let msg = match args.version.as_deref() {
                Some(v) => format!("schema version {v} not found for event type {}", args.id),
                None => format!(
                    "no CURRENT or FINALISING schema version found for event type {}",
                    args.id
                ),
            };
            return Ok(CallToolResult::error(vec![Content::text(msg)]));
        };

        let schema = spec
            .get("schema")
            .cloned()
            .unwrap_or(serde_json::Value::Null);
        let text = serde_json::to_string_pretty(&schema).unwrap_or_else(|_| schema.to_string());
        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    #[tool(
        description = "List webhook subscriptions configured in FlowCatalyst (scoped to the authenticated client unless an admin clientId is provided)."
    )]
    async fn list_subscriptions(
        &self,
        Parameters(args): Parameters<ListSubscriptionsArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.list_subscriptions(args.client_id.as_deref()).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(description = "Get detailed information about a specific subscription.")]
    async fn get_subscription(
        &self,
        Parameters(args): Parameters<GetByIdArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.get_subscription(&args.id).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "List applications registered in FlowCatalyst. Defaults to active-only; pass active=false to include inactive."
    )]
    async fn list_applications(
        &self,
        Parameters(args): Parameters<ListApplicationsArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.list_applications(args.active).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(description = "List roles registered in FlowCatalyst. Optionally filter by source.")]
    async fn list_roles(
        &self,
        Parameters(args): Parameters<ListRolesArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.list_roles(args.source.as_deref()).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Get a single role by ID, including its assigned permissions. Use list_roles to discover IDs."
    )]
    async fn get_role(
        &self,
        Parameters(args): Parameters<GetByIdArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.get_role(&args.id).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Fetch the CURRENT OpenAPI document for an application (defaults to 'platform' — the FlowCatalyst control-plane API). This is the canonical 'what can be done' surface: every endpoint, parameter, and response shape."
    )]
    async fn get_openapi(
        &self,
        Parameters(args): Parameters<GetOpenApiArgs>,
    ) -> Result<CallToolResult, McpError> {
        let code = args.application_code.as_deref().unwrap_or("platform");
        match self.api.get_openapi(code).await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Identify the calling principal: id, type (USER/SERVICE), scope, roles, accessible clients, and accessible applications. Start here to learn what the agent itself can do."
    )]
    async fn whoami(
        &self,
        Parameters(_): Parameters<EmptyArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.whoami().await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "List applications the calling principal has access to. Combined with whoami, tells the agent which apps it can actually act against right now."
    )]
    async fn list_my_applications(
        &self,
        Parameters(_): Parameters<EmptyArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self.api.list_my_applications().await {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }

    #[tool(
        description = "Everything an agent needs to call into an application: metadata + defaultBaseUrl, the CURRENT OpenAPI document (if synced), assignable roles, and CURRENT event types. Missing sub-resources come back as null instead of failing the whole call."
    )]
    async fn get_application_capabilities(
        &self,
        Parameters(args): Parameters<GetApplicationCapabilitiesArgs>,
    ) -> Result<CallToolResult, McpError> {
        match self
            .api
            .get_application_capabilities(&args.application_code)
            .await
        {
            Ok(v) => Ok(json_text(v)),
            Err(e) => Ok(error_text(e)),
        }
    }
}

#[tool_handler]
impl ServerHandler for FcMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new(
            "flowcatalyst",
            env!("CARGO_PKG_VERSION"),
        ))
        .with_instructions(
            "FlowCatalyst MCP server. Read-only discovery of the platform:\n\
             - whoami returns the calling principal: id, type, scope, roles, \
               and the clients + applications it can act against. Start here.\n\
             - list_my_applications scopes that down to apps the principal has \
               access to right now.\n\
             - get_application_capabilities(code) bundles app metadata + \
               defaultBaseUrl + OpenAPI + assignable roles + event types — \
               everything needed to call into the named application.\n\
             - get_openapi (default applicationCode='platform') returns the \
               full REST API specification for an application.\n\
             - list_applications / list_roles + get_role enumerate the platform-\
               wide registry independently of the caller's access.\n\
             - list_event_types / get_event_type / get_schema explore the event \
               catalog and JSON Schemas.\n\
             - list_subscriptions / get_subscription show webhook configuration.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        let resources = vec![
            RawResource::new(
                "flowcatalyst://openapi/platform",
                "Platform OpenAPI".to_string(),
            )
            .no_annotation(),
            RawResource::new("flowcatalyst://applications", "Applications".to_string())
                .no_annotation(),
            RawResource::new("flowcatalyst://roles", "Roles".to_string()).no_annotation(),
            RawResource::new("flowcatalyst://event-types", "Event Types".to_string())
                .no_annotation(),
            RawResource::new("flowcatalyst://subscriptions", "Subscriptions".to_string())
                .no_annotation(),
        ];
        Ok(ListResourcesResult {
            resources,
            next_cursor: None,
            meta: None,
        })
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        let uri = request.uri.clone();
        let result = match uri.as_str() {
            "flowcatalyst://event-types" => {
                self.api
                    .list_event_types(&ListEventTypesFilters::default())
                    .await
            }
            "flowcatalyst://subscriptions" => self.api.list_subscriptions(None).await,
            "flowcatalyst://applications" => self.api.list_applications(None).await,
            "flowcatalyst://roles" => self.api.list_roles(None).await,
            other => {
                if let Some(id) = other.strip_prefix("flowcatalyst://event-types/") {
                    self.api.get_event_type(id).await
                } else if let Some(id) = other.strip_prefix("flowcatalyst://subscriptions/") {
                    self.api.get_subscription(id).await
                } else if let Some(code) = other.strip_prefix("flowcatalyst://openapi/") {
                    self.api.get_openapi(code).await
                } else if let Some(id) = other.strip_prefix("flowcatalyst://roles/") {
                    self.api.get_role(id).await
                } else if let Some(code) = other.strip_prefix("flowcatalyst://applications/") {
                    self.api.get_application_by_code(code).await
                } else {
                    return Err(McpError::resource_not_found(
                        "resource_not_found",
                        Some(json!({ "uri": uri })),
                    ));
                }
            }
        };

        match result {
            Ok(v) => {
                let text = serde_json::to_string_pretty(&v).unwrap_or_else(|_| v.to_string());
                Ok(ReadResourceResult::new(vec![ResourceContents::text(
                    text, uri,
                )]))
            }
            Err(e) => Err(McpError::internal_error(e.to_string(), None)),
        }
    }
}

fn json_text(value: serde_json::Value) -> CallToolResult {
    let text = serde_json::to_string_pretty(&value).unwrap_or_else(|_| value.to_string());
    CallToolResult::success(vec![Content::text(text)])
}

fn error_text(e: anyhow::Error) -> CallToolResult {
    CallToolResult::error(vec![Content::text(e.to_string())])
}
