//! Shared test harness for fc-platform integration tests.
//!
//! `TestApp::setup()` spins up a PostgreSQL testcontainer, runs migrations,
//! builds the full production router via `build_platform_routes`, and
//! exposes helpers for:
//!   - generating auth tokens (anchor / partner / service account)
//!   - sending requests against the router
//!   - reading response bodies
//!   - inspecting `msg_events` and `aud_logs` to verify UoW persistence
//!
//! Include this module in an integration test file with:
//!   #[path = "support/mod.rs"]
//!   mod support;

#![allow(dead_code)] // helpers are used selectively across test files

use std::sync::Arc;

use axum::{
    body::Body,
    http::{Method, Request, Response, StatusCode},
    Router,
};
use http_body_util::BodyExt;
use serde::Serialize;
use serde_json::Value;
use testcontainers::runners::AsyncRunner;
use testcontainers::ContainerAsync;
use testcontainers_modules::postgres::Postgres;
use tower::ServiceExt;

use fc_platform::auth::auth_service::{AuthConfig, AuthService};
use fc_platform::auth::oidc_service::OidcService;
use fc_platform::auth::oidc_sync_service::OidcSyncService;
use fc_platform::auth::password_service::PasswordService;
use fc_platform::domain::{Principal, UserScope};
use fc_platform::repository::Repositories;
use fc_platform::shared::authorization_service::AuthorizationService;
use fc_platform::shared::database::{create_pool, run_migrations, MigrationProfile};
use fc_platform::shared::middleware::{AppState, AuthLayer};
use fc_platform::shared::server_setup::{
    build_platform_routes, AuthServices, PlatformRoutesConfig,
};
use fc_platform::usecase::PgUnitOfWork;

/// A fully-wired test application sharing a live Postgres container.
///
/// Drops the container when `TestApp` is dropped.
pub struct TestApp {
    pub pool: sqlx::PgPool,
    pub router: Router,
    pub auth_service: Arc<AuthService>,
    pub repos: Repositories,
    pub unit_of_work: Arc<PgUnitOfWork>,
    _container: ContainerAsync<Postgres>,
}

impl TestApp {
    /// Start a fresh container + migrated DB + full router.
    pub async fn setup() -> Self {
        let container = Postgres::default()
            .with_db_name("flowcatalyst_test")
            .with_user("test")
            .with_password("test")
            .start()
            .await
            .expect("failed to start Postgres container");

        let host = container.get_host().await.expect("host");
        let port = container.get_host_port_ipv4(5432).await.expect("port");
        let database_url = format!("postgresql://test:test@{}:{}/flowcatalyst_test", host, port);

        let pool = create_pool(&database_url).await.expect("pool");
        run_migrations(&pool, MigrationProfile::Production)
            .await
            .expect("migrations");

        let repos = Repositories::new(&pool);
        let unit_of_work = Arc::new(PgUnitOfWork::new(pool.clone()));

        // Seed the platform application row — the BFF developer routes expect
        // it to exist; production binaries seed it before serving HTTP.
        fc_platform::shared::database::seed_platform_application(&pool)
            .await
            .expect("seed platform application");
        let platform_application_id = repos
            .application_repo
            .find_by_code("platform")
            .await
            .expect("find platform app")
            .expect("platform app row")
            .id;

        // Test-only auth services: in-memory RSA keys (generated by AuthConfig)
        // + the same wiring init_auth_services produces.
        let (private_key, public_key) =
            AuthConfig::load_or_generate_rsa_keys(None, None).expect("rsa keys");
        let auth_service = Arc::new(AuthService::new(AuthConfig {
            rsa_private_key: Some(private_key),
            rsa_public_key: Some(public_key),
            rsa_public_key_previous: None,
            secret_key: String::new(),
            issuer: "flowcatalyst-test".to_string(),
            audience: "flowcatalyst-test".to_string(),
            access_token_expiry_secs: 3600,
            session_token_expiry_secs: 28800,
            refresh_token_expiry_secs: 86400,
        }));
        let authz_service = Arc::new(AuthorizationService::new(repos.role_repo.clone()));

        let auth_services = AuthServices {
            auth: auth_service.clone(),
            authz: authz_service.clone(),
            password: Arc::new(PasswordService::default()),
            oidc_sync: Arc::new(OidcSyncService::new(
                repos.principal_repo.clone(),
                repos.idp_role_mapping_repo.clone(),
            )),
            oidc: Arc::new(OidcService::new()),
        };

        let platform_routes = build_platform_routes(
            &repos,
            &auth_services,
            &unit_of_work,
            PlatformRoutesConfig {
                rate_limit_store: Arc::new(
                    fc_platform::shared::rate_limit_store::NoopRateLimitStore,
                ),
                rate_limit_policies: Arc::new(
                    fc_platform::shared::rate_limit_store::RateLimitPolicies::from_env(),
                ),
                session_cookie_secure: false,
                session_cookie_same_site: PlatformRoutesConfig::DEFAULT_SAME_SITE.to_string(),
                session_token_expiry_secs: PlatformRoutesConfig::DEFAULT_SESSION_EXPIRY_SECS,
                static_dir: None,
                oidc_login_external_base_url: None,
                well_known_external_base_url: "http://localhost".to_string(),
                password_reset_external_base_url: "http://localhost".to_string(),
            },
            platform_application_id,
        );

        let (base_router, _openapi) = platform_routes.build();
        let router = base_router.layer(AuthLayer::new(AppState {
            auth_service: auth_service.clone(),
            authz_service,
        }));

        Self {
            pool,
            router,
            auth_service,
            repos,
            unit_of_work,
            _container: container,
        }
    }

    // ── Token helpers ─────────────────────────────────────────────────────

    /// Token for an anchor-scoped admin principal.
    pub fn anchor_token(&self) -> String {
        let principal = Principal::new_user("admin@flowcatalyst.test", UserScope::Anchor);
        self.auth_service
            .generate_access_token(&principal)
            .expect("anchor token")
    }

    /// Token for an anchor-scoped principal with the `platform:*:*:*`
    /// wildcard permission. Seeds a role on first call; the token carries
    /// the role name so the authz middleware resolves it to ADMIN_ALL.
    ///
    /// Use this when testing endpoints that check `can_read_*` / `can_write_*`
    /// (permission-based) rather than `require_anchor` (scope-based).
    pub async fn anchor_admin_token(&self) -> String {
        use fc_platform::role::entity::{permissions, AuthRole};
        use fc_platform::service_account::entity::RoleAssignment;

        let role_code = "platform:test-admin";

        // Idempotent seed so repeated calls in the same test don't duplicate.
        if self
            .repos
            .role_repo
            .find_by_name(role_code)
            .await
            .ok()
            .flatten()
            .is_none()
        {
            let role = AuthRole::new("platform", "test-admin", "Test Admin")
                .with_permission(permissions::ADMIN_ALL);
            self.repos
                .role_repo
                .insert(&role)
                .await
                .expect("insert test-admin role");
        }

        let mut principal = Principal::new_user("admin@flowcatalyst.test", UserScope::Anchor);
        principal.roles = vec![RoleAssignment::new(role_code)];
        self.auth_service
            .generate_access_token(&principal)
            .expect("anchor-admin token")
    }

    /// Token for a partner-scoped principal (cross-client access).
    pub fn partner_token(&self) -> String {
        let principal = Principal::new_user("partner@flowcatalyst.test", UserScope::Partner);
        self.auth_service
            .generate_access_token(&principal)
            .expect("partner token")
    }

    /// Token for a client-scoped user principal.
    pub fn client_user_token(&self, client_id: &str) -> String {
        let principal = Principal::new_user("user@flowcatalyst.test", UserScope::Client)
            .with_client_id(client_id);
        self.auth_service
            .generate_access_token(&principal)
            .expect("client token")
    }

    /// Token for a service account principal (used by SDKs).
    pub fn service_account_token(&self, client_id: &str) -> String {
        let principal =
            Principal::new_service("svc-test", "Test Service").with_client_id(client_id);
        self.auth_service
            .generate_access_token(&principal)
            .expect("svc token")
    }

    // ── Request helpers ───────────────────────────────────────────────────

    pub async fn get(&self, path: &str, token: &str) -> Response<Body> {
        self.send(Method::GET, path, Some(token), None::<()>).await
    }

    pub async fn post<B: Serialize>(&self, path: &str, token: &str, body: B) -> Response<Body> {
        self.send(Method::POST, path, Some(token), Some(body)).await
    }

    pub async fn put<B: Serialize>(&self, path: &str, token: &str, body: B) -> Response<Body> {
        self.send(Method::PUT, path, Some(token), Some(body)).await
    }

    pub async fn delete(&self, path: &str, token: &str) -> Response<Body> {
        self.send(Method::DELETE, path, Some(token), None::<()>)
            .await
    }

    /// Unauthenticated GET (useful for auth-failure tests).
    pub async fn get_unauth(&self, path: &str) -> Response<Body> {
        self.send(Method::GET, path, None, None::<()>).await
    }

    async fn send<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        token: Option<&str>,
        body: Option<B>,
    ) -> Response<Body> {
        let mut builder = Request::builder().method(method).uri(path);
        if let Some(t) = token {
            builder = builder.header("authorization", format!("Bearer {}", t));
        }
        let req = if let Some(b) = body {
            let json = serde_json::to_string(&b).expect("serialize body");
            builder
                .header("content-type", "application/json")
                .body(Body::from(json))
                .expect("build req")
        } else {
            builder.body(Body::empty()).expect("build req")
        };
        self.router.clone().oneshot(req).await.expect("oneshot")
    }

    // ── DB inspection helpers ─────────────────────────────────────────────

    /// Count `msg_events` rows whose `subject` column contains the given
    /// fragment. Use the aggregate id as the fragment — events subjects are
    /// formatted like `platform.client.clt_123`.
    pub async fn event_count_for(&self, subject_fragment: &str) -> i64 {
        let pattern = format!("%{}%", subject_fragment);
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM msg_events WHERE subject LIKE $1")
            .bind(&pattern)
            .fetch_one(&self.pool)
            .await
            .expect("count msg_events");
        row.0
    }

    /// Count `aud_logs` rows for a given aggregate entity_id.
    pub async fn audit_count_for(&self, entity_id: &str) -> i64 {
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM aud_logs WHERE entity_id = $1")
            .bind(entity_id)
            .fetch_one(&self.pool)
            .await
            .expect("count aud_logs");
        row.0
    }

    /// Count rows in `msg_events` matching a given event `type` (e.g.
    /// `platform:iam:oauth-client:created`).
    pub async fn event_count_by_type(&self, event_type: &str) -> i64 {
        let row: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM msg_events WHERE type = $1")
            .bind(event_type)
            .fetch_one(&self.pool)
            .await
            .expect("count msg_events by type");
        row.0
    }
}

// ── Body helpers (pure functions, not on TestApp) ────────────────────────────

/// Read the full response body as JSON. Panics if the body isn't JSON —
/// use `read_bytes` first if you need to inspect raw output.
pub async fn read_json(resp: Response<Body>) -> (StatusCode, Value) {
    let status = resp.status();
    let bytes = resp
        .into_body()
        .collect()
        .await
        .expect("collect")
        .to_bytes();
    if bytes.is_empty() {
        return (status, Value::Null);
    }
    let json = serde_json::from_slice(&bytes).unwrap_or_else(|e| {
        panic!(
            "response body was not JSON: {} — body: {}",
            e,
            String::from_utf8_lossy(&bytes)
        )
    });
    (status, json)
}

/// Assert the response status — panics with the JSON body on mismatch.
pub async fn assert_status(resp: Response<Body>, expected: StatusCode) -> Value {
    let (status, body) = read_json(resp).await;
    assert_eq!(
        status, expected,
        "expected {}, got {} — body: {}",
        expected, status, body
    );
    body
}
